### ISSUE TITLE
Content from a parent project is displayed without a path in the child project

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2072]
1. Create a parent project then create a subproject.
2. Go to subproject context and save folder with name  `folder1`.
![image](https://user-images.githubusercontent.com/3728712/88680166-dc04f280-d0f8-11ea-943d-e2eb6d9084d5.png)

3 Go to parent context and  open new folder wizard , type the same name `folder1` and save it 
![image](https://user-images.githubusercontent.com/3728712/88680360-13739f00-d0f9-11ea-944c-a85826fb26f2.png)

4. Switch to the subproject context again: 

BUG: 
1) **Folder without path is displayed in the subproject:** 

![image](https://user-images.githubusercontent.com/3728712/88680535-44ec6a80-d0f9-11ea-98e7-02670b06880e.png)

```
om.enonic.xp.content.ContentAlreadyExistsException: Content at path [/folder1] already exists
        at com.enonic.xp.core.impl.content.RenameContentCommand.execute(RenameContentCommand.java:62)
        at com.enonic.xp.core.impl.content.ContentServiceImpl.rename(ContentServiceImpl.java:746)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.doSyncRenamed(ParentProjectSynchronizer.java:153)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.lambda$syncRenamed$3(ParentProjectSynchronizer.java:139)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.lambda$syncRenamed$4(ParentProjectSynchronizer.java:135)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.syncRenamed(ParentProjectSynchronizer.java:132)
        at com.enonic.xp.core.impl.project.ProjectNodeEventListener.lambda$handleContentEvent$5(ProjectNodeEventListener.java:126)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.enonic.xp.core.impl.project.ProjectNodeEventListener.lambda$handleContentEvent$6(ProjectNodeEventListener.java:106)
        at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
        at com.enonic.xp.core.impl.project.ProjectNodeEventListener.handleContentEvent(ProjectNodeEventListener.java:93)
        at com.enonic.xp.core.impl.project.ProjectNodeEventListener.lambda$handleEventType$1(ProjectNodeEventListener.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
17:37:33.401 INFO  c.e.x.c.i.c.UpdateContentCommand - *** DataValidationError: name is required
17:38:25.049 WARN  c.e.x.c.i.p.ParentProjectSyncActivator - Error while project sync.
com.enonic.xp.content.ContentAlreadyExistsException: Content at path [/folder1] already exists
        at com.enonic.xp.core.impl.content.RenameContentCommand.execute(RenameContentCommand.java:62)
        at com.enonic.xp.core.impl.content.ContentServiceImpl.rename(ContentServiceImpl.java:746)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.doSyncRenamed(ParentProjectSynchronizer.java:153)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.lambda$doSync$2(ParentProjectSynchronizer.java:117)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.doSync(ParentProjectSynchronizer.java:108)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.lambda$syncWithChildren$0(ParentProjectSynchronizer.java:87)
        at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
        at com.enonic.xp.core.impl.project.ParentProjectSynchronizer.syncWithChildren(ParentProjectSynchronizer.java:75)
        at com.enonic.xp.core.impl.project.ParentProjectSyncTask.doSync(ParentProjectSyncTask.java:70)
        at com.enonic.xp.core.impl.project.ParentProjectSyncTask.lambda$run$2(ParentProjectSyncTask.java:57)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.enonic.xp.core.impl.project.ParentProjectSyncTask.lambda$run$3(ParentProjectSyncTask.java:55)
        at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
        at com.enonic.xp.core.impl.project.ParentProjectSyncTask.run(ParentProjectSyncTask.java:38)
        














```

**Comment by ashklianko** [comment]
Not sure there's issue at all: content path in child project is occupied but inherited content is still created in all children layers (though with default generated unnamed path). Probably backend error should be hidden in that case, but there's nothing to fix on frontend. @alansemenov ?

**Comment by alansemenov** [comment]
this should have been fixed in the backend.
