### ISSUE TITLE
Errors in server log after creating and initializing nested layers.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2273]
**This bug is reproduced when there is quite a lot of content in a parent project.**

1. Install Features .
2. Open Setting and create 2 new layers(in default project) in sequence.

![image](https://user-images.githubusercontent.com/3728712/92899819-d143ba00-f427-11ea-817e-461a50c649b9.png)

3. Error appears in the server log when two layers  are initializing: 

`12:01:59.753 WARN  c.e.x.c.i.c.ParentProjectSyncActivator - Error while project sync.
com.enonic.xp.node.NodeIdExistsException: Node 32169e70-49e1-444c-a6ac-d38f22438134 already exists
	at com.enonic.xp.repo.impl.node.CreateNodeCommand.verifyNotExistsAlready(CreateNodeCommand.java:212)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
	at com.enonic.xp.repo.impl.node.NodeHelper.runAsAdmin(NodeHelper.java:15)
	at com.enonic.xp.repo.impl.node.CreateNodeCommand.execute(CreateNodeCommand.java:68)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.doCreate(NodeServiceImpl.java:462)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.create(NodeServiceImpl.java:450)
	at com.enonic.xp.core.impl.content.CreateContentCommand.doCreateContent(CreateContentCommand.java:146)
	at com.enonic.xp.core.impl.content.CreateContentCommand.doExecute(CreateContentCommand.java:124)
	at com.enonic.xp.core.impl.content.CreateContentCommand.execute(CreateContentCommand.java:97)
	at com.enonic.xp.core.impl.content.ContentServiceImpl.create(ContentServiceImpl.java:252)
	at com.enonic.xp.project.ParentProjectSynchronizer.lambda$doSyncCreated$20(ParentProjectSynchronizer.java:381)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.project.ParentProjectSynchronizer.lambda$doSyncCreated$21(ParentProjectSynchronizer.java:371)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.project.ParentProjectSynchronizer.doSyncCreated(ParentProjectSynchronizer.java:367)
	at com.enonic.xp.project.ParentProjectSynchronizer.lambda$doSync$3(ParentProjectSynchronizer.java:168)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.project.ParentProjectSynchronizer.doSync(ParentProjectSynchronizer.java:149)
	at com.enonic.xp.project.ParentProjectSynchronizer.lambda$syncWithChildren$2(ParentProjectSynchronizer.java:133)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
	at com.enonic.xp.project.ParentProjectSynchronizer.syncWithChildren(ParentProjectSynchronizer.java:107)
	at com.enonic.xp.project.ParentProjectSynchronizer.syncRoot(ParentProjectSynchronizer.java:100)
	at com.enonic.xp.core.impl.content.ParentProjectSyncTask.doSync(ParentProjectSyncTask.java:75)
	at com.enonic.xp.core.impl.content.ParentProjectSyncTask.lambda$run$2(ParentProjectSyncTask.java:61)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.enonic.xp.core.impl.content.ParentProjectSyncTask.lambda$run$3(ParentProjectSyncTask.java:59)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
	at com.enonic.xp.core.impl.content.ParentProjectSyncTask.run(ParentProjectSyncTask.java:42)
	at com.enonic.xp.core.internal.concurrent.SimpleRecurringJobScheduler$WrappedRunnable.run(SimpleRecurringJobScheduler.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by sgauruseu** [comment]
I pulled  changes in XP , this issue does not reproduce in the new build
