### ISSUE TITLE
Option Set -  Incorrect radio button behavior  in multi selection

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3024]
**Case 1**
1. Select Features and open new wizard for Option Set
2. Unselect the `Option 2` radio
3. Click on `Save` button

![image](https://user-images.githubusercontent.com/3728712/113009984-23101f80-9181-11eb-8d7d-51be19cb8af2.png)

**BUG** - **Option 2 radio gets selected again after the saving.**

4. Click on `Option 2` again  - 
**BUG** - `Option 2` remains selected and  subheader  is not correct now, `option 2` is duplicated 

![image](https://user-images.githubusercontent.com/3728712/113010874-dbd65e80-9181-11eb-8859-c598f9998815.png)

 **Case 2** 
This case is reproducing when Option 2 contains occurrences of htmlArea inputs, for example
````
  <option name="option_2">
          <label>Option 2</label>
          <default>true</default>
          <items>
            <input name="htmlarea_2_4" type="HtmlArea">
              <label>HTML content 2:4</label>
              <occurrences minimum="2" maximum="4"/>
            </input>
          </items>
        </option>
````

Unselect the `Option 2 ` and save the content 

**BUG- 500 error appears after saving the content**

![image](https://user-images.githubusercontent.com/3728712/113112018-69ad5a80-9211-11eb-999f-df811a454593.png)

````
5:05:34.323 ERROR c.e.x.j.i.e.JsonExceptionMapper - NullPointerException
java.lang.NullPointerException: null
        at com.enonic.xp.core.impl.content.validate.OccurrenceValidator.validateInputOccurrences(OccurrenceValidator.java:160)
        at com.enonic.xp.core.impl.content.validate.OccurrenceValidator.validateInput(OccurrenceValidator.java:76)
        at com.enonic.xp.core.impl.content.validate.OccurrenceValidator.validate(OccurrenceValidator.java:57)
        at com.enonic.xp.core.impl.content.validate.OccurrenceValidator.validateFormOptionSetSelection(OccurrenceValidator.java:114)
        at com.enonic.xp.core.impl.content.validate.OccurrenceValidator.validateFormOptionSet(OccurrenceValidator.java:8
````

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1878](https://github.com/enonic/lib-admin-ui/issues/1878) via [**ZenHub**](https://www.zenhub.com/)
