### ISSUE TITLE
Exception in version history panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#393]
1. Install SuperHero
2. Open Filter Panel and check `Post` (Comment, Landing Page)
3. Select any post-content and try to open Versions Widget

![image](https://user-images.githubusercontent.com/3728712/55553543-246cf580-56e9-11e9-83d5-4153545f60b0.png)

**BUG**:
**NullPointerException in server.log and 
500 error in console**

java.lang.NullPointerException: null
        at com.enonic.xp.core.impl.content.ContentVersionFactory.doCreateContentVersion(ContentVersionFactory.java:53)
        at com.enonic.xp.core.impl.content.ContentVersionFactory.create(ContentVersionFactory.java:43)
        at com.enonic.xp.core.impl.content.ContentVersionFactory.create(ContentVersionFactory.java:33)
        at com.enonic.xp.core.impl.content.FindContentVersionsCommand.doGetContentVersions(FindContentVersionsCommand.java:60)
        at com.enonic.xp.core.impl.content.FindContentVersionsCommand.execute(FindContentVersionsCommand.java:37)
        at com.enonic.xp.core.impl.content.ContentServiceImpl.getVersions(ContentServiceImpl.java:897)
        at com.enonic.xp.admin.impl.rest.resource.content.ContentResource.getContentVersionsForView(ContentResource.java:1234)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/xp #7063](https://github.com/enonic/xp/issues/7063) via [**ZenHub**](https://www.zenhub.com/)
