### ISSUE TITLE
Error in console after reverting a site or shortcut

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4912]
1. Create a simple site (select a controller) or create a shortcut with a target 
2. Open versions panel and revert the previous version

https://user-images.githubusercontent.com/3728712/181719301-be1e0216-205d-49d4-a055-3f7118bdbb44.mp4

BUG: error in console after reverting versions 
```
main.js:52 TypeError: Cannot read properties of undefined (reading 'getId')
    at archive.js:110:783809
    at main.js:54:1552188
    at Array.forEach (<anonymous>)
    at VersionContext.notifyActiveVersionChanged (main.js:54:1552167)
    at VersionContext.setActiveVersion (main.js:54:1551713)
    at main.js:54:1566121
    at _fulfilled (vendors.main~editor.js:110:6786)
    at vendors.main~editor.js:110:6820
    at Promise.r.promiseDispatch (vendors.main~editor.js:110:5296)
    at vendors.main~editor.js:110:4432
```

**Comment by sgauruseu** [comment]
can not reproduce it in latest version
