### ISSUE TITLE
ContentSelector inputType fails if content is in root (not site)

### ISSUE THREAD

**Issue by rymsha** [enonic/app-contentstudio#6081]
```
java.lang.RuntimeException: Could not resolve parent site for content: Content
        at com.enonic.xp.app.contentstudio.rest.resource.content.ContentSelectorQueryJsonToContentQueryConverter.resolveParentSiteIfNeeded(ContentSelectorQueryJsonToContentQueryConverter.java:161)
        at com.enonic.xp.app.contentstudio.rest.resource.content.ContentSelectorQueryJsonToContentQueryConverter.createQueryExpr(ContentSelectorQueryJsonToContentQueryConverter.java:147)
        at com.enonic.xp.app.contentstudio.rest.resource.content.ContentSelectorQueryJsonToContentQueryConverter.createQuery(ContentSelectorQueryJsonToContentQueryConverter.java:69)
        at com.enonic.xp.app.contentstudio.rest.resource.content.ContentResource.findContentsBySelectorQuery(ContentResource.java:1367)
        at com.enonic.xp.app.contentstudio.rest.resource.content.ContentResource.selectorQuery(ContentResource.java:12
```

**Comment by rymsha** [comment]
It only happens when content with content-selector is under another content
