### ISSUE TITLE
Error in console after inserting a text component using DnD 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7433]
1. Open a site with a selected controller , open Context Window
2. Insert new text component via DnD - drag  `Rich Text Editor` item in `Insert` tab  then drop it in `Live Edit`

![image](https://github.com/enonic/app-contentstudio/assets/3728712/4fd03fbd-a1a0-4671-8f8d-2a449b5ef259)

BUG - Error appears in console  after dnd new text component 

```
Cannot read properties of null (reading 'on')
    at HtmlEditor.modifyImagePlugin (VM642 editor.js:2:909546)
    at new HtmlEditor (VM642 editor.js:2:908998)
    at VM642 editor.js:2:923608
    at _fulfilled (VM641 vendors.main~editor.js:2:168557)
    at VM641 vendors.main~editor.js:2:168591
    at Promise.i.promiseDispatch (VM641 vendors.main~editor.js:2:167067)
    at VM641 vendors.main~editor.js:2:168455
    at runSingle (VM641 vendors.main~editor.js:2:162328)
    at MessagePort.flush (VM641 vendors.main~editor.js:2:162244)
```

**Comment by ashklianko** [comment]
Introduced in 5.1.0,
