### ISSUE TITLE
Issues in Compare Version dialog (non-slickgrid)

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7822]
**Issue 1 - ` OK ` should not appear after clicking on the same options in the dropdown options:**
 - Create a folder, then open Compare Versions dialog
 - Click on the dropdown handle and expand the combobox
 - Click on the `Previous version` - the first item in  options
 
![image](https://github.com/user-attachments/assets/f69b0a28-8084-40cf-afa5-c54b8dab92e7)

 click on `OK` button  - the button remains visible

![image](https://github.com/user-attachments/assets/7de08698-3153-4f61-9c84-4e9206b268c2)

**Issue 2   -  `IllegalArgumentException` thrown after clicking on `Revert` button**

**Steps -**  - Create a folder, then open Compare Versions dialog
              - Click on the left Revert button
              
![image](https://github.com/user-attachments/assets/01d6cb01-2350-4bdd-b3d3-5e44cd6e9f9a)
 

```java.lang.IllegalArgumentException: UUID format incorrect: ab77ff2a-9a66-4362-9674-86c8e759b4ef:alias|1
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
        at com.enonic.xp.node.UUID.check(UUID.java:44)
        at com.enonic.xp.node.UUID.<init>(UUID.java:36)
        at com.enonic.xp.node.NodeVersionId.<init>(NodeVersionId.java:17)
        at com.enonic.xp.node.NodeVersionId.from(NodeVersionId.java:33)
        at com.enonic.xp.core.impl.content.GetContentByIdAndVersionIdCommand.execute(GetContentByIdAndVersionIdCommand.java:37)```

![image](https://github.com/user-attachments/assets/cccc2d06-bb72-4e1e-8415-4316ed6c40e9)

**Comment by sgauruseu** [comment]
All tests passed
